# Generated by Django 4.2.9 on 2024-01-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
