# Generated by Django 4.2.9 on 2024-01-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_member_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
